subdomain_discovery:
  # available tools are Sublist3r, amass, assetfinder, subfinder
  # Usage of many tools may improve the results but also may take longer time to scan
  uses_tool: [subfinder, sublist3r]
  thread: 10
  # Your wordlist shortname for amass active enumeration, ignore if you are using passive enumeration
  wordlist: default
  # Get the shortname for the config file from configurations module
  amass_config: config_short_name

port_scan:
  # will be made available in future release
  # scan_ports available options are top-100, top-1000, full or custom like
  # [80, 443]
  ports: [top-100]
  # if you want to exclude certain ports, usage: exclude_ports: [80, 443]
  exclude_ports: null
  thread: 10

visual_identification:
  # currently runs aquatone
  # available options for ports are small, medium, large, xlarge
  port: xlarge
  thread: 2

subdomain_takeover:
  # only subjack is supported at this time
  thread: 1

dir_file_search:
  extensions: [php, asp, aspx, txt, conf, db, sql, json]
  recursive: false
  recursive_level: 1
  thread: 100
  wordlist: default

fetch_url:
  uses_tool: [all]
  intensity: aggressive

vulnerability_scan:
  concurrent: 10
  template: all
  severity: all
